<?php require_once 'templates/header.phtml'?>
    <div class="about tarjeta">
        <ul>
            <?php foreach ($usuarios as $item) { ?>
                <li><?= $item->email?> | <?= $item->nivel ?> | <button>Eliminar</button> </li>    
           <?php }?>
        </ul>
    </div>
    <div class="about tarjeta">
        <ul>
            <?php foreach ($generos as $genero) { ?>
                <li><?= $genero->genero?> | <button>Eliminar</button> </li>    
           <?php }?>
        </ul>
    </div>
    <div class="about tarjeta">
        <ul>
            <?php foreach ($discos as $disco) { ?>
                <li><?= $disco->nombre?> | <?= $disco->autor?> | <?= $disco->genero?> | <?= $disco->precio?> | <button>Eliminar</button> </li>    
           <?php }?>
        </ul>
    </div>
<?php require_once 'templates/footer.phtml'?>