<?php
    require_once 'templates/header.phtml';
    require_once 'templates/formFiltro.phtml';
    require_once './config.php';
?>

<section>
    <?php foreach($discos as $disco){?>
        <div class="verDisco">
            <h3><?= $disco->nombre?></h3>
            <p>
                Autor: <?= $disco->autor ?>  
                (<?= $disco->genero ?>)  |  Precio: <?= $disco->precio?>
            </p>
            <img src="./img/disco-img.jpg" alt="">
            <?php if(isset($_SESSION['logueado'])&($_SESSION['logueado']->nivel ==='admin')){ ?>   
                <a href="delete/<?= $disco->id?>" type="button" class="btn btn-danger">Borrar</a>
            <?php } ?>
            <?php if(isset($_SESSION)&($_SESSION['logueado']->nivel === 'user')){ ?>   
                <a href="buy/<?= $disco->id?>" type="button" class="btn btn-success">Comprar</a>
            <?php } ?>
        </div>

    <?php } ?>

</section>

<?php
    require 'templates/footer.phtml';
?>