<?php 
require_once './app/models/generos.model.php'; ?>
<div>
    <h3 class="ms-5">Ordenar por:</h3> 
    <a href="orderTitulo" class="btn btn-success boton ms-5" >Titulo</a>
    <a href="orderAutor" class="btn btn-success boton" >Autor</a>
    <a href="orderPrecio" class="btn btn-success boton" >Precio</a>
</div>

<form action="filtro" method="POST" class="mb-3 formulario">
    <?php 
    $model = new GenerosModel();
    $generos=$model->getCategorias(); 
    ?>
    <label> Filtrar por Genero </label>
    <select name="genero" class="form-select">
        <option  value="" selected></option>
        <?php foreach ($generos as $genero) { ?>
           <option value="<?= $genero->id?>"><?= $genero->categoria?></option>;<?php
        }?>
    </select>
    <button type="submit" class="btn btn-info boton">Filtrar</button>
</form>