<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comercio de discos musicales</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <nav class="titulo container-fluid">
            <h1 class="col-12 text-center">Discos Musicales E-Comerce</h1>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <a class="navbar-brand" href="home">Home</a>
                <?php if(isset($_SESSION['logueado'])&&($_SESSION['logueado']->nivel == 'admin')){ ?>
                <a class="navbar-brand" href="configuracion">Configuracion</a>
                <?php } ?>
                <a class="navbar-brand" href="about">About</a>
                <?php if(isset($_SESSION['logueado'])){
                    ?><a class="navbar-brand" href="logout">Logout</a><?php
                } else { 
                    ?><a class="navbar-brand" href="login">Login</a><?php
                }?>
            </nav>  
        </nav>
    </header>