<?php 
require_once 'templates/header.phtml';
require_once './app/models/users.model.php';
require_once './config.php';

?>
<section class="container">
   
    <form action="auth" method="POST" class="mb-3 formulario">
        <label class="form-label">Usuario</label>
        <input type="text" name="email" class="form-control" required/>
        <labelclass="form-label">Password</label>
        <input type="password" name="password" class="form-control" required/>
        <button type="submit" class="btn btn-primary boton">Login !</button>
    </form> 
</section>

<?php
require_once 'templates/footer.phtml';
?>